/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modelo;

import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * Persona Value Object.
  * This class is value object representing database table PERSONA 
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class Persona implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int ID_PERSONA;
    private String IDENTIFICACION;
    private String PRIMERNOMBRE;
    private String SEGUNDONOMBRE;
    private String APELLIDOS;
    private int TELEFONO;
    private String DIRECCION;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public Persona () {

    }

    public Persona (int ID_PERSONAIn) {

          this.ID_PERSONA = ID_PERSONAIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getID_PERSONA() {
          return this.ID_PERSONA;
    }
    public void setID_PERSONA(int ID_PERSONAIn) {
          this.ID_PERSONA = ID_PERSONAIn;
    }

    public String getIDENTIFICACION() {
          return this.IDENTIFICACION;
    }
    public void setIDENTIFICACION(String IDENTIFICACIONIn) {
          this.IDENTIFICACION = IDENTIFICACIONIn;
    }

    public String getPRIMERNOMBRE() {
          return this.PRIMERNOMBRE;
    }
    public void setPRIMERNOMBRE(String PRIMERNOMBREIn) {
          this.PRIMERNOMBRE = PRIMERNOMBREIn;
    }

    public String getSEGUNDONOMBRE() {
          return this.SEGUNDONOMBRE;
    }
    public void setSEGUNDONOMBRE(String SEGUNDONOMBREIn) {
          this.SEGUNDONOMBRE = SEGUNDONOMBREIn;
    }

    public String getAPELLIDOS() {
          return this.APELLIDOS;
    }
    public void setAPELLIDOS(String APELLIDOSIn) {
          this.APELLIDOS = APELLIDOSIn;
    }

    public int getTELEFONO() {
          return this.TELEFONO;
    }
    public void setTELEFONO(int TELEFONOIn) {
          this.TELEFONO = TELEFONOIn;
    }

    public String getDIRECCION() {
          return this.DIRECCION;
    }
    public void setDIRECCION(String DIRECCIONIn) {
          this.DIRECCION = DIRECCIONIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int ID_PERSONAIn,
          String IDENTIFICACIONIn,
          String PRIMERNOMBREIn,
          String SEGUNDONOMBREIn,
          String APELLIDOSIn,
          int TELEFONOIn,
          String DIRECCIONIn) {
          this.ID_PERSONA = ID_PERSONAIn;
          this.IDENTIFICACION = IDENTIFICACIONIn;
          this.PRIMERNOMBRE = PRIMERNOMBREIn;
          this.SEGUNDONOMBRE = SEGUNDONOMBREIn;
          this.APELLIDOS = APELLIDOSIn;
          this.TELEFONO = TELEFONOIn;
          this.DIRECCION = DIRECCIONIn;
    }


    /** 
     * hasEqualMapping-method will compare two Persona instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(Persona valueObject) {

          if (valueObject.getID_PERSONA() != this.ID_PERSONA) {
                    return(false);
          }
          if (this.IDENTIFICACION == null) {
                    if (valueObject.getIDENTIFICACION() != null)
                           return(false);
          } else if (!this.IDENTIFICACION.equals(valueObject.getIDENTIFICACION())) {
                    return(false);
          }
          if (this.PRIMERNOMBRE == null) {
                    if (valueObject.getPRIMERNOMBRE() != null)
                           return(false);
          } else if (!this.PRIMERNOMBRE.equals(valueObject.getPRIMERNOMBRE())) {
                    return(false);
          }
          if (this.SEGUNDONOMBRE == null) {
                    if (valueObject.getSEGUNDONOMBRE() != null)
                           return(false);
          } else if (!this.SEGUNDONOMBRE.equals(valueObject.getSEGUNDONOMBRE())) {
                    return(false);
          }
          if (this.APELLIDOS == null) {
                    if (valueObject.getAPELLIDOS() != null)
                           return(false);
          } else if (!this.APELLIDOS.equals(valueObject.getAPELLIDOS())) {
                    return(false);
          }
          if (valueObject.getTELEFONO() != this.TELEFONO) {
                    return(false);
          }
          if (this.DIRECCION == null) {
                    if (valueObject.getDIRECCION() != null)
                           return(false);
          } else if (!this.DIRECCION.equals(valueObject.getDIRECCION())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass Persona, mapping to table PERSONA \n");
        out.append("Persistent attributes: \n"); 
        out.append("ID_PERSONA = " + this.ID_PERSONA + "\n"); 
        out.append("IDENTIFICACION = " + this.IDENTIFICACION + "\n"); 
        out.append("PRIMERNOMBRE = " + this.PRIMERNOMBRE + "\n"); 
        out.append("SEGUNDONOMBRE = " + this.SEGUNDONOMBRE + "\n"); 
        out.append("APELLIDOS = " + this.APELLIDOS + "\n"); 
        out.append("TELEFONO = " + this.TELEFONO + "\n"); 
        out.append("DIRECCION = " + this.DIRECCION + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        Persona cloned = new Persona();

        cloned.setID_PERSONA(this.ID_PERSONA); 
        if (this.IDENTIFICACION != null)
             cloned.setIDENTIFICACION(new String(this.IDENTIFICACION)); 
        if (this.PRIMERNOMBRE != null)
             cloned.setPRIMERNOMBRE(new String(this.PRIMERNOMBRE)); 
        if (this.SEGUNDONOMBRE != null)
             cloned.setSEGUNDONOMBRE(new String(this.SEGUNDONOMBRE)); 
        if (this.APELLIDOS != null)
             cloned.setAPELLIDOS(new String(this.APELLIDOS)); 
        cloned.setTELEFONO(this.TELEFONO); 
        if (this.DIRECCION != null)
             cloned.setDIRECCION(new String(this.DIRECCION)); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}


